services:
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
  taxmanagement:
    image: ${DOCKER_REGISTRY-}taxmanagement
    build:
      context: .
      dockerfile: Tax Management/Dockerfile
    depends_on:
      - db
